// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Attempt struct {
	ID            string `json:"id"`
	EventIid      string `json:"eventIid"`
	AttemptNumber int32  `json:"attemptNumber"`
}

type Endpoint struct {
	ID     string  `json:"id"`
	Tenant *Tenant `json:"tenant"`
	URL    string  `json:"url"`
}

type Query struct {
}

type Tenant struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Tier      string      `json:"tier"`
	Endpoints []*Endpoint `json:"endpoints"`
}
